### ISSUE TITLE
Updater roadmap

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/updater#52]
### Updater 1.1

- [ ] improve documentation and what this tool does
- [ ] rollbacks for all steps (#9)
- [ ] look into the "shipped files" issue - we should not hardcode this in the updater but use the signature.json
    - [ ] ignore custom apps folders (#40)
    - [ ] ignore assets folder (#23)
- [ ] polishing:
    - [ ] no right side bar needed (#43)
    - [ ] inline retry button (#41)
- [ ] integration tests for the web UI (#10)
- [ ] use custom user agent to check for updates (for rough usage stats)
- [ ] respect the server response for disabled updater - (can additionally be used to only make update notifications show but not the update itself work (in case of bugs) - we have already a flag in the response but I think we ignore that one atm)

### Updater 2.0

- [ ] download tar ball before going into maintenance mode
- [ ] check for breaking dependencies - PHP version, PHP modules, ... 
    - [ ] should we rely on the rollback to do that job automatically? 
      => I'd say the update server can hand a list of requirements. Can be similar to how we do it in the server atm... Rollback should only be last resort.!
- [ ] check sha sum of downloaded file
- [ ] check signature of sha sum 
- [ ] wishlist: check if patched updater is available and update that first then (additional step and also using signatures etc.)

Thanks to @rullzer a& @LukasReschke for the feedback

**Comment by jospoortvliet** [comment]
Perhaps add translations too? Not a huge prio, but nice :wave:

**Comment by tflidd** [comment]
>     * check for breaking dependencies - PHP version, PHP modules, ...

It seems that is already implemented:
https://help.nextcloud.com/t/solved-update-upgrade-from-15-to-16-missing-button-link/66225

However not communicated to the user.

**Comment by MorrisJobke** [comment]
> [x] download tar ball before going into maintenance mode

done

> [x] check sha sum of downloaded file

done



> * check signature of sha sum

done

> * 
> * [x]  use custom user agent to check for updates (for rough usage stats)

done
